### PR TITLE
use babel-preset-react-hmre

### PR DESCRIPTION
**Pull request by danmartinez101**
Created this babel preset based on @gaearon's comment https://github.com/gaearon/babel-plugin-react-transform/issues/46#issuecomment-152834076

https://github.com/danmartinez101/babel-preset-react-hmre

### CODE REVIEW

**Comment by thejameskyle** [comment]
Doesn't this just get in the way of having a more diverse ecosystem of react transforms? By limiting it to just the two by @gaearon that means you're preventing people from adding more to the configuration.

I leaning towards no on this one.

**Comment by danmartinez101** [comment]
As far as I can tell, there wouldn't be issues with including additional presets. It is possible that I'm overlooking something.

In this demo, I split the error catching(redbox) and HMR into different presets and things still seem to work as expected.
split react presets

**Comment by gaearon** [comment]
I think having a preset is beneficial because 95% users want just these two and are intimidated by configuration.

**Comment by danmartinez101** [comment]
Just want to clarify that I wasn't suggesting breaking the preset included here down into two different presets, just that using this preset wouldn't preclude the use of other react-transform plugin presets so the ecosystem shouldn't be harmed at all.

Like gaearon mentioned, the configuration ( react-transform, not necessarily babel config ) is intimidating to new users. It is yet another bump in the road for adopters of this (react, redux, hmr, etc) ecosystem and this type of preset is just a way to smooth out that bump. As soon as users want more power, they can dive in and figure out how to add other transforms or extend this one very easily.

**Comment by gaearon** [comment]
Yeah I'm for this. Advanced users will figure out how to customize it.

**Pull request merged**
