### PR TITLE
Babel 6 Update

### PR DESCRIPTION
**Pull request by justingreenberg**
**Ready to merge! :tada:**

### Babel 6
- [x] gaearon/babel-plugin-react-transform
- [x] update docs (and clean up ie. #70)
- [x] use new configuration syntax in `.babelrc` 
- [x] update babel packages and related dependencies
- [x] wait for `acorn-to-esprima` and `eslint` support

### CODE REVIEW

**Comment by danmartinez101** [comment]
I tested this PR on my app and it worked like a charm. The app has a mix of `createClass` and `extends React.Component` based components and the react-transform-hmr worked fine with this PR so those seem to work.

**Comment by justingreenberg** [comment]
@danmartinez101 thanks for the feedback, you're one step ahead of me i was actually just going to suggest testing against this branch in the react-transform discussion :+1:

**Comment by TaopaiC** [comment]
I think it doesn't need babel-preset-stage-0 now since it doesn't use decorator.

**Comment by justingreenberg** [comment]
@TaopaiC good catch—removed `stage-0` preset and rebased PR

**Comment by amoshche** [comment]
ERROR in ./src/App.js
Module build failed: TypeError: C:/home/Alexey/work/js/react-transform-boilerplate/src/App.js: Property arguments[0] of CallExpression expected node to be of a type ["Expression","SpreadElement"] but instead got "ClassDeclaration"
...
at wrapComponent (C:\home\Alexey\work\js\react-transform-boilerplate\node_modules\babel-plugin-react-transform\lib\index.js:53:14)

**Comment by hbin** [comment]
Why not PR to babel-plugin-react-transform?

**Comment by weblancaster** [comment]
@danmartinez101 I'm also testing on my end but I keep getting `imports[1] for react-transform-catch-errors does not look like a React component` I'm using webpack middleware on express dev env.

```javascript
{
  presets: [
    'es2015',
    'stage-0',
    'react'
  ],
  "env": {
    "development": {
      "plugins": [
        ["react-transform", {
          "transforms": [{
            "transform": "react-transform-hmr",
            "imports": ["react"],
            "locals": ["module"]
          }, {
            "transform": "react-transform-catch-errors",
            "imports": ["react", "redbox-react"]
          }]
        }]
      ]
    }
  }
}
```

**Comment by justingreenberg** [comment]
@weblancaster everything is working fine—are you referring this this PR? or your own project? this PR has been updated a couple times, maybe try again...

```bash
git clone https://github.com/justingreenberg/react-transform-boilerplate.git
cd react-transform-boilerplate
git checkout babel-6
npm install
npm run start
```

site should be running at `localhost:3000`, hot reloading and error catching should be working. if you still run into errors, please report them back here with os, node/npm/v8 versions and complete stack trace

**Comment by vagusX** [comment]
babel-plugin-react-transform updated, how is it going now?

**Comment by weblancaster** [comment]
I tried this PR not the master (master is supposed to work but is "outdated") @justingreenberg

**Comment by thejameskyle** [comment]
Okay I've published `babel-plugin-react-transform@2.0.0-beta1` and created an example project: https://github.com/thejameskyle/babel-setup-react-transform

**Comment by justingreenberg** [comment]
@thejameskyle awesome, updated package.json and tested against fresh install, this is ready to be merged :smile: thanks again for everything

**Pull request merged**
