### PR TITLE
Upgrade react to v0.14

### PR DESCRIPTION
**Pull request by ZillDing**

### CODE REVIEW

**Comment by gaearon** [comment]
Thanks. It's not ready yet though—waiting for React Transform stuff to get compatible.
It'll take about a week.

**Comment by ZillDing** [comment]
Oops~ Thanks for replying. Looking forward! Then should I close this pull request or just leave it here?

**Comment by gaearon** [comment]
Just leave it here.

**Comment by thebigredgeek** [comment]
Bump?

**Comment by gaearon** [comment]
Bumps won't help me ship the code sooner, sorry.

**Comment by debradley** [comment]
Just curious because I don't know - what's involved other then updating a few dependency version numbers in package.json?

**Comment by gaearon** [comment]
The point of this boilerplate is to show hot reloading with React Transform.
React Transform is not yet updated to fully support 0.14.
Hot reloading 0.14 functional components won't work.

I got it merged though—by popular demand. :wink:

**Comment by ZillDing** [comment]
Thank! I have been using it for some time and haven't met any problem so far. Your React Transform is pretty solid. Thanks for the great work.

**Pull request merged**
